GEMINI_API_KEY = "AIzaSyAHY9K2NU6l17bQAq5NJOC9towRRzriCcg"
GROQ_API_KEY = "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"
BACKEND_PASSWORD = "ciaociao"
SUPABASE_URL = "https://ixbnhssahprksdjhfsic.supabase.co"
SUPABASE_KEY = "sb_publishable_2-l0tleTP9VcSbbje6HoFQ_A5pwBAxV"
