GEMINI_API_KEY = "AIzaSyBK-2S8yP2eisEjJgO6lRjIlly34najO_Y"
GROQ_API_KEY = "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"
BACKEND_PASSWORD = "ciaociao"
SUPABASE_URL = "https://ixbnhssahprksdjhfsic.supabase.co"
SUPABASE_KEY = "sb_publishable_2-l0tleTP9VcSbbje6HoFQ_A5pwBAxV"